"""C++ generator of cppFUN models.

Public API: generate_fun_cpp. Expressions and derivatives come from
cppde_graph; the entry points are documented in R/cppFUN.R.
"""

import os
from io import StringIO

import cppde_emit as em
import cppde_graph as cg

_USING_STD = (
    "    using std::exp; using std::log; using std::sqrt; using std::pow;\n"
    "    using std::sin; using std::cos; using std::tan;\n"
    "    using std::asin; using std::acos; using std::atan; using std::atan2;\n"
    "    using std::sinh; using std::cosh; using std::tanh;\n"
    "    using std::asinh; using std::acosh; using std::atanh;\n"
    "    using std::floor; using std::ceil;\n"
    "    using std::abs; using std::max; using std::min;\n")

_USING_AD = (
    "    using cppde::exp; using cppde::log; using cppde::sqrt; using cppde::pow;\n"
    "    using cppde::sin; using cppde::cos; using cppde::tan;\n"
    "    using cppde::asin; using cppde::acos; using cppde::atan;\n"
    "    using cppde::sinh; using cppde::cosh; using cppde::tanh;\n"
    "    using cppde::asinh; using cppde::acosh; using cppde::atanh;\n"
    "    using cppde::abs; using cppde::max; using cppde::min;\n")


class FunModel:
    """Parsed outputs over per-observation variables and shared parameters.

    Variable i prints as x_obs[i], parameter k as p[k], cotangent i as _w[i].

    Attributes:
        variables, parameters, out_names: name lists.
        g: cppde_graph.Graph; roots: node per output; ad: cppde_graph.AD.
    """

    def __init__(self, exprs, variables, parameters):
        self.variables = list(variables)
        self.parameters = list(parameters)
        self.out_names = list(exprs.keys())
        g = self.g = cg.Graph()
        sym = {}
        for k, p in enumerate(self.parameters):
            sym[p] = g.param(k)
        for i, v in enumerate(self.variables):
            sym[v] = g.state(i)
        self.parser = cg.Parser(g, sym)
        self.ad = cg.AD(g)
        self.roots = [self.parser.parse(str(exprs[n]), label=n) for n in self.out_names]

    @staticmethod
    def slot(at):
        k = at[0]
        if k == cg.STATE:
            return "x_obs[%d]" % at[1]
        if k == cg.PARAM:
            return "p[%d]" % at[1]
        if k == cg.VEC and at[1] == "w":
            return "_w[%d]" % at[2]
        raise em.EmitError("no slot for leaf " + cg.KIND_NAMES[k])

    def render(self, stmts, level, indent):
        pr = em.Printer(self.g, self.slot, style="template", ad_level=level)
        return em.render_cpp(stmts, pr, "T", indent=indent)


# =====================================================================
# Public interface
# =====================================================================

def generate_fun_cpp(exprs, variables, parameters=None,
                     ad=False, deriv2=False, vjp=False,
                     modelname="model", outdir=None, version="1.0.0"):
    """Write `<outdir>/<modelname>.cpp` for a cppFUN model.

    Args:
        exprs: dict output name -> expression, or list (outputs f1, f2, ...).
        variables: per-observation symbols.
        parameters: shared symbols, fixed ones included.
        ad: emit `_eval_ad` (dual); with `deriv2` also `_eval_ad2` (dual2nd).
        vjp: emit `_vjp` and `_vjp_ad`.
        outdir: output directory (required).

    Returns:
        dict with `filename` (absolute path) and `modelname`.
    """
    if isinstance(variables, str):
        variables = [variables]
    variables = variables or []
    if parameters is None:
        parameters = []
    elif isinstance(parameters, str):
        parameters = [parameters]
    if isinstance(exprs, list):
        exprs = {"f%d" % (i + 1): e for i, e in enumerate(exprs)}
    elif not isinstance(exprs, dict):
        raise TypeError("exprs must be a dict or list")
    if outdir is None:
        raise ValueError("outdir must be provided explicitly")

    model = FunModel(exprs, variables, parameters)
    cpp_code = _generate_cpp_code(model, ad, deriv2, vjp, modelname, version)

    os.makedirs(outdir, exist_ok=True)
    filename = os.path.join(outdir, "%s.cpp" % modelname)
    with open(filename, "w", encoding="utf-8") as f:
        f.write(cpp_code)
    return {"filename": os.path.abspath(filename), "modelname": modelname}


# =====================================================================
# C++ source assembly
# =====================================================================

def _generate_cpp_code(model, ad, deriv2, vjp, modelname, version):
    """Source text of the model; `vjp` is independent of `ad`."""
    ctx = model
    out_names = model.out_names
    buf = StringIO()
    emit_ad = ad
    emit_ad2 = ad and deriv2
    emit_vjp = vjp
    level = 1 if (emit_ad or emit_vjp) else 0

    buf.write("/** Code auto-generated by cppDE %s **/\n\n" % version)
    buf.write("#include <cmath>\n")
    buf.write("#include <algorithm>\n")
    buf.write("#include <limits>\n")
    buf.write("#include <vector>\n")
    buf.write("#define R_NO_REMAP\n")
    buf.write("#include <R.h>\n")
    buf.write("#include <Rinternals.h>\n")
    buf.write("#include <cppde/cppde_scalar_ops.hpp>\n")
    if emit_ad or emit_vjp:
        buf.write("#ifdef _OPENMP\n#include <omp.h>\n#endif\n")
        buf.write("#include <cppde/cppde_dual_math.hpp>\n")
        buf.write("#include <cppde/cppde_dual_expr.hpp>\n")
    if emit_ad2:
        buf.write("#include <cppde/cppde_dual2nd.hpp>\n")
        buf.write("#include <cppde/cppde_dual2nd_math.hpp>\n")
        buf.write("#include <cppde/cppde_dual2nd_expr.hpp>\n")
    buf.write("\n")
    buf.write("// Modelname: %s\n" % modelname)
    buf.write("// Variables: %s\n" % (", ".join(ctx.variables) or "none"))
    buf.write("// Parameters: %s\n" % (", ".join(ctx.parameters) or "none"))
    buf.write("// Outputs: %s\n\n" % ", ".join(out_names))

    _write_eval_template(buf, model, modelname, emit_ad or emit_vjp, level)

    buf.write("extern \"C\" {\n\n")
    NAN_ = "std::numeric_limits<double>::quiet_NaN()"
    _write_guarded(
        buf,
        lambda b: _write_eval_function(b, out_names, ctx, modelname),
        "std::fill(y, y + (size_t)(*n) * (size_t)(*l), %s);" % NAN_,
    )
    if emit_ad:
        _write_eval_ad_impl(buf, out_names, ctx, modelname)
        _write_guarded(
            buf,
            lambda b: _write_eval_ad_function(b, out_names, ctx, modelname),
            """const size_t ny_ = (size_t)(*n_obs_p) * (size_t)(*n_out_p);
std::fill(y, y + ny_, %s);
std::fill(dy, dy + ny_ * (size_t)(*n_theta_p), %s);""" % (NAN_, NAN_),
        )
        _write_eval_ad_batch(buf, modelname)
    if emit_vjp:
        # Templates cannot have C linkage.
        buf.write("} // extern \"C\"\n\n")
        _write_vjp_impl(buf, model, modelname)
        _write_vjp_ad_impl(buf, modelname, ctx, out_names)
        buf.write("extern \"C\" {\n\n")
        _write_guarded(
            buf,
            lambda b: _write_vjp_function(b, modelname),
            """const size_t ny_ = (size_t)(*n_obs_p) * (size_t)(*n_out_p);
const size_t ns_ = (size_t)(*n_seed_p);
std::fill(y, y + ny_, %s);
std::fill(wx, wx + (size_t)(*n_obs_p) * (size_t)(*n_vars_p) * ns_, %s);
std::fill(wp, wp + (size_t)(*n_params_p) * ns_, %s);""" % (NAN_, NAN_, NAN_),
        )
    if emit_ad2:
        _write_eval_ad2_function(buf, out_names, ctx, modelname, as_impl=True)
        _write_guarded(
            buf,
            lambda b: _write_eval_ad2_function(b, out_names, ctx, modelname),
            """const size_t ny_ = (size_t)(*n_obs_p) * (size_t)(*n_out_p);
const size_t nt_ = (size_t)(*n_theta_p);
std::fill(y, y + ny_, %s);
std::fill(dy, dy + ny_ * nt_, %s);
std::fill(d2y, d2y + ny_ * nt_ * nt_, %s);""" % (NAN_, NAN_, NAN_),
        )
        _write_eval_ad2_batch(buf, modelname)

    _write_call_entries(
        buf, modelname,
        n_vars=len(ctx.variables), n_params=len(ctx.parameters),
        n_out=len(out_names),
        ad=emit_ad, ad2=emit_ad2, vjp=emit_vjp)

    buf.write("} // extern \"C\"\n")
    return buf.getvalue()


def eval_statements(model):
    """Body of `_eval_one<T>`: y_local[i] = output i."""
    stores = [(("vec", "y_local", i), r, "=") for i, r in enumerate(model.roots)]
    stmts, names = em.schedule(model.g, stores, prefix="_t")
    return [("block", names, stmts)]


def _write_eval_template(buf, model, modelname, ad, level):
    """`<model>_eval_one<T>(x_obs, p, y_local)`, instantiated for double and,
    with `ad`, for the dual types."""
    buf.write("namespace {\n")
    buf.write("template <typename T>\n")
    buf.write("inline void %s_eval_one(const T* x_obs, const T* p, T* y_local) {\n"
              % modelname)
    buf.write(_USING_STD)
    if ad:
        buf.write(_USING_AD)
    buf.write("    (void)x_obs; (void)p;\n\n")
    for line in model.render(eval_statements(model), level, "    "):
        buf.write(line + "\n")
    buf.write("}\n")
    buf.write("} // anonymous namespace\n\n")


def vjp_statements(model, cast="(size_t)"):
    """(per-observation statements, per-seed statements) of `_vjp_impl`;
    `cast` prefixes the index products."""
    g = model.g
    w = [g.vec("w", i) for i in range(len(model.roots))]
    adj = model.ad.vjp(model.roots, w, cg.F_STATE | cg.F_PARAM)
    stores = []
    for leaf in sorted(adj, key=lambda n: g.attr[n]):
        k, idx = g.attr[leaf][0], g.attr[leaf][1]
        if k == cg.STATE:
            t = ("vec", "wx", "obs + %sn_obs * (%d + %sn_vars * s)" % (cast, idx, cast))
        else:
            t = ("vec", "wp", "%d + %sn_params * s" % (idx, cast))
        stores.append((t, adj[leaf], "+="))
    stmts, names = em.schedule(g, stores, prefix="_v")
    outer, inner = em.split_loop(g, stmts, cg.F_VEC)
    return [("block", names, outer)], [("block", names, inner)]


def _write_vjp_impl(buf, model, modelname):
    """`<model>_vjp_impl<T>`: y and the cotangents wx (per observation) and
    wp (summed over observations) for each seed w[., ., s].

    Layouts (column-major): x [n_obs, n_vars], w [n_obs, n_out, n_seed],
    y [n_obs, n_out], wx [n_obs, n_vars, n_seed], wp [n_params, n_seed].
    """
    n_vars = len(model.variables)
    n_out = len(model.out_names)
    outer, inner = vjp_statements(model)
    buf.write("template<class T>\n")
    buf.write("static void %s_vjp_impl(const T* x, const T* p,\n" % modelname)
    buf.write("                         const T* w,\n")
    buf.write("                         T* y, T* wx, T* wp,\n")
    buf.write("                         int n_obs, int n_vars, int n_params,\n")
    buf.write("                         int n_out, int n_seed) {\n")
    buf.write(_USING_STD)
    buf.write(_USING_AD)
    buf.write("    (void)n_vars; (void)n_params; (void)n_out; (void)x; (void)p;\n\n")
    buf.write("    const size_t ns_ = (size_t)(n_seed > 0 ? n_seed : 1);\n")
    buf.write("    for (size_t i_ = 0; i_ < (size_t)n_obs * (size_t)n_vars * ns_; ++i_)\n")
    buf.write("        wx[i_] = T(0.0);\n")
    buf.write("    for (size_t i_ = 0; i_ < (size_t)n_params * ns_; ++i_)\n")
    buf.write("        wp[i_] = T(0.0);\n\n")
    buf.write("    for (int obs = 0; obs < n_obs; ++obs) {\n")
    if n_vars > 0:
        buf.write("        T x_obs_buf[%d];\n" % n_vars)
        buf.write("        for (int j = 0; j < n_vars; ++j)\n")
        buf.write("            x_obs_buf[j] = x[obs + (size_t)n_obs * j];\n")
        buf.write("        const T* x_obs = x_obs_buf;\n")
        buf.write("        (void)x_obs;\n")
    buf.write("        T y_obs[%d];\n" % max(n_out, 1))
    buf.write("        %s_eval_one<T>(%s, p, y_obs);\n"
              % (modelname, "x_obs" if n_vars > 0 else "nullptr"))
    buf.write("        for (int i = 0; i < n_out; ++i)\n")
    buf.write("            y[obs + (size_t)n_obs * i] = y_obs[i];\n")
    for line in model.render(outer, 1, "        "):
        buf.write(line + "\n")
    buf.write("        for (int s = 0; s < n_seed; ++s) {\n")
    buf.write("            const T* w_s = w + (size_t)n_obs * (size_t)n_out * s;\n")
    buf.write("            T _w[%d];\n" % max(n_out, 1))
    buf.write("            for (int i = 0; i < n_out; ++i)\n")
    buf.write("                _w[i] = w_s[obs + (size_t)n_obs * i];\n")
    buf.write("            (void)_w;\n")
    for line in model.render(inner, 1, "            "):
        buf.write(line + "\n")
    buf.write("        }\n")
    buf.write("    }\n}\n\n")


def _write_guarded(buf, emit_fn, nan_fill):
    """Wrap an emitted extern-C entry body in try/catch.

    .C() has no error channel and these bodies allocate, so an escaping
    bad_alloc would terminate the R session.  `nan_fill` runs in the
    function's own scope and marks the output non-finite instead.
    """
    tmp = StringIO()
    emit_fn(tmp)
    text = tmp.getvalue()

    head, sep, rest = text.partition("{\n")   # first brace opens the body
    if not sep:
        raise RuntimeError("guarded emitter produced no function body")
    body = rest.rstrip()
    if not body.endswith("}"):
        raise RuntimeError("guarded emitter did not end on a closing brace")
    body = body[:-1].rstrip("\n")             # drop its own closer

    buf.write(head + "{\n")
    buf.write("    try {\n")
    buf.write(body + "\n")
    buf.write("    } catch (...) {\n")
    for line in nan_fill.strip().splitlines():
        buf.write("        " + line.strip() + "\n")
    buf.write("    }\n}\n\n")


def _write_eval_function(buf, out_names, ctx, modelname):
    """Generate extern-C eval entry point (double instantiation of the helper).

    Layouts (R column-major):
      x [n_obs, n_vars]  -> obs + n_obs * j    (as R holds it)
      y [n_obs, n_out]   -> obs + n_obs * i    (time-first output)
    """
    n_vars = len(ctx.variables)
    n_out = len(out_names)

    buf.write(f"void {modelname}_eval(double* x, double* y, double* p, int* n, int* k, int* l) {{\n")
    buf.write("    const int n_obs = *n;\n")
    buf.write("    const int n_vars = *k;\n")
    buf.write("    const int n_out  = *l;\n")
    buf.write("    (void)n_vars;  // suppress unused warning\n\n")
    buf.write(f"    double y_local[{max(n_out, 1)}];\n")
    buf.write("    for (int obs = 0; obs < n_obs; obs++) {\n")

    if n_vars > 0:
        buf.write(f"        double x_obs_buf[{n_vars}];\n")
        buf.write("        for (int j = 0; j < n_vars; ++j)\n")
        buf.write("            x_obs_buf[j] = x[obs + (size_t)n_obs * j];\n")
        buf.write("        const double* x_obs = x_obs_buf;\n")
    else:
        buf.write("        const double* x_obs = nullptr;\n")

    buf.write(f"        {modelname}_eval_one<double>(x_obs, p, y_local);\n")
    buf.write("        for (int i = 0; i < n_out; ++i)\n")
    buf.write("            y[obs + (size_t)n_obs * i] = y_local[i];\n")
    buf.write("    }\n}\n\n")


def _write_eval_ad_impl(buf, out_names, ctx, modelname):
    """
    Generate extern-C AD entry point. Takes upstream seeds dX (per-obs state
    sensitivities) and dP (parameter Jacobian) and fills value + dY/dtheta
    in a single forward-mode AD pass per observation.

    Layouts (R column-major):
      x   [n_obs, n_vars]                    -> obs + n_obs * j      (as R holds it)
      p   [n_params]                         -> j
      dX  [n_obs, n_vars, n_theta]           -> obs + n_obs * (j + n_vars * k)
      dP  [n_params, n_theta]                -> j + n_params * k
      y   [n_obs, n_out]                     -> obs + n_obs * i
      dy  [n_obs, n_out, n_theta]            -> obs + n_obs * (i + n_out * k)
    """
    n_vars = len(ctx.variables)
    n_params = len(ctx.parameters)
    n_out = len(out_names)

    ad_t = "cppde::dual<double, 0>"

    # The body lives in an impl taking values, so the .C entry and the batch
    # entry share it. The batch entry calls it from worker threads.
    buf.write(
        f"static void {modelname}_eval_ad_impl(const double* x, const double* p,\n"
        f"                         const double* dX, const double* dP,\n"
        f"                         double* y, double* dy,\n"
        f"                         int n_obs, int n_vars, int n_params,\n"
        f"                         int n_out, int n_theta) {{\n"
    )
    buf.write(f"    using AD = {ad_t};\n")
    buf.write("    (void)n_vars; (void)n_params; (void)n_out;\n")
    buf.write("    (void)dX; (void)dP;\n\n")

    # dual<double, 0> tangent buffers come from the thread-local arena, freed by one
    # outer scope guard at function exit. A per-obs scope would leave the AD vectors,
    # which persist across iterations, holding dangling tan_ pointers after the pop.
    buf.write("    cppde::dual_arena::scope _eval_ad_scope;\n")

    buf.write(f"    std::vector<AD> x_ad({n_vars});\n")
    buf.write(f"    std::vector<AD> p_ad({n_params});\n")
    buf.write(f"    std::vector<AD> y_ad({n_out});\n\n")

    # Seed parameters once (constant across obs).
    if n_params > 0:
        buf.write("    // Seed parameters (time-invariant).\n")
        buf.write("    for (int j = 0; j < n_params; ++j) {\n")
        buf.write("        p_ad[j].x() = p[j];\n")
        buf.write("        if (n_theta > 0) {\n")
        buf.write("            p_ad[j].diff(0, n_theta);\n")
        buf.write("            for (int k = 0; k < n_theta; ++k) {\n")
        buf.write("                p_ad[j][k] = dP[j + n_params * k];\n")
        buf.write("            }\n")
        buf.write("        }\n")
        buf.write("    }\n\n")

    buf.write("    for (int obs = 0; obs < n_obs; ++obs) {\n")
    if n_vars > 0:
        buf.write("        for (int j = 0; j < n_vars; ++j) {\n")
        buf.write("            x_ad[j].x() = x[obs + (size_t)n_obs * j];\n")
        buf.write("            if (n_theta > 0) {\n")
        buf.write("                x_ad[j].diff(0, n_theta);\n")
        buf.write("                for (int k = 0; k < n_theta; ++k) {\n")
        buf.write("                    x_ad[j][k] = dX[obs + (size_t)n_obs * (j + (size_t)n_vars * k)];\n")
        buf.write("                }\n")
        buf.write("            }\n")
        buf.write("        }\n")
    buf.write(f"        {modelname}_eval_one<AD>(x_ad.data(), p_ad.data(), y_ad.data());\n")
    buf.write("        for (int i = 0; i < n_out; ++i) {\n")
    buf.write("            y[obs + (size_t)n_obs * i] = y_ad[i].val();\n")
    buf.write("            for (int k = 0; k < n_theta; ++k) {\n")
    # .d(k) on cppde::dual<double, 0> returns the k-th tangent, or a thread-local
    # zero when the dual is non-depend. Raw operator[] would dereference tan_
    # unconditionally and fault for an output constant in all parameters.
    buf.write("                dy[obs + (size_t)n_obs * (i + (size_t)n_out * k)] = y_ad[i].d(k);\n")
    buf.write("            }\n")
    buf.write("        }\n")
    buf.write("    }\n}\n\n")

def _write_eval_ad_function(buf, out_names, ctx, modelname):
    buf.write(
        f"void {modelname}_eval_ad(double* x, double* p, double* dX, double* dP,\n"
        f"                         double* y, double* dy,\n"
        f"                         int* n_obs_p, int* n_vars_p, int* n_params_p,\n"
        f"                         int* n_out_p, int* n_theta_p) {{\n"
        f"    {modelname}_eval_ad_impl(x, p, dX, dP, y, dy, *n_obs_p, *n_vars_p,\n"
        f"                             *n_params_p, *n_out_p, *n_theta_p);\n"
        "}\n\n"
    )


def _write_call_entries(buf, modelname, n_vars, n_params, n_out,
                        ad=False, ad2=False, vjp=False):
    """Emit .Call entries beside the .C ones.

    `.C()` copies every argument in and every result out; on a chain evaluated
    once per condition that dominates the actual arithmetic. These take the
    inputs by reference and allocate the results once. The .C entries stay so
    an object file built by an older cppDE keeps working.
    """
    buf.write(f"""SEXP {modelname}_eval_c(SEXP xS, SEXP pS, SEXP nS) {{
  int n_obs = INTEGER(nS)[0], n_vars = {n_vars}, n_out = {n_out};
  SEXP y = PROTECT(Rf_allocMatrix(REALSXP, n_obs, n_out));
  {modelname}_eval(REAL(xS), REAL(y), REAL(pS), &n_obs, &n_vars, &n_out);
  UNPROTECT(1);
  return y;
}}

""")
    if ad:
        buf.write(f"""SEXP {modelname}_eval_ad_c(SEXP xS, SEXP pS, SEXP dXS, SEXP dPS,
                       SEXP nS, SEXP nthS) {{
  const int n_obs = INTEGER(nS)[0], n_theta = INTEGER(nthS)[0];
  const int n_vars = {n_vars}, n_params = {n_params}, n_out = {n_out};
  const int nt1 = n_theta > 0 ? n_theta : 1;
  SEXP y = PROTECT(Rf_allocMatrix(REALSXP, n_obs, n_out));
  SEXP d = PROTECT(Rf_allocVector(INTSXP, 3));
  INTEGER(d)[0] = n_obs; INTEGER(d)[1] = n_out; INTEGER(d)[2] = nt1;
  SEXP dy = PROTECT(Rf_allocArray(REALSXP, d));
  {modelname}_eval_ad_impl(REAL(xS), REAL(pS),
      Rf_isNull(dXS) ? nullptr : REAL(dXS),
      Rf_isNull(dPS) ? nullptr : REAL(dPS),
      REAL(y), REAL(dy), n_obs, n_vars, n_params, n_out, n_theta);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, 2));
  SET_VECTOR_ELT(out, 0, y);
  SET_VECTOR_ELT(out, 1, dy);
  UNPROTECT(4);
  return out;
}}

""")
    if vjp:
        buf.write(f"""SEXP {modelname}_vjp_c(SEXP xS, SEXP pS, SEXP wS,
                   SEXP nS, SEXP nsS) {{
  const int n_obs = INTEGER(nS)[0], n_seed = INTEGER(nsS)[0];
  const int n_vars = {n_vars}, n_params = {n_params}, n_out = {n_out};
  const int ns1 = n_seed > 0 ? n_seed : 1;
  SEXP y = PROTECT(Rf_allocMatrix(REALSXP, n_obs, n_out));
  SEXP d = PROTECT(Rf_allocVector(INTSXP, 3));
  INTEGER(d)[0] = n_obs; INTEGER(d)[1] = n_vars; INTEGER(d)[2] = ns1;
  SEXP wx = PROTECT(Rf_allocArray(REALSXP, d));
  SEXP wp = PROTECT(Rf_allocMatrix(REALSXP, n_params, ns1));
  {modelname}_vjp_impl<double>(REAL(xS), Rf_isNull(pS) ? nullptr : REAL(pS), REAL(wS),
      REAL(y), REAL(wx), REAL(wp), n_obs, n_vars, n_params, n_out, n_seed);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, 3));
  SET_VECTOR_ELT(out, 0, y);
  SET_VECTOR_ELT(out, 1, wx);
  SET_VECTOR_ELT(out, 2, wp);
  UNPROTECT(5);
  return out;
}}

SEXP {modelname}_vjp_ad_c(SEXP xS, SEXP pS, SEXP wS, SEXP vxS, SEXP vpS,
                   SEXP dwS, SEXP nS, SEXP nsS, SEXP ndS) {{
  const int n_obs = INTEGER(nS)[0], n_seed = INTEGER(nsS)[0];
  const int n_dir = INTEGER(ndS)[0];
  const int n_vars = {n_vars}, n_params = {n_params}, n_out = {n_out};
  const int ns1 = n_seed > 0 ? n_seed : 1;
  const int nd1 = n_dir > 0 ? n_dir : 1;
  SEXP y = PROTECT(Rf_allocMatrix(REALSXP, n_obs, n_out));
  SEXP d3 = PROTECT(Rf_allocVector(INTSXP, 3));
  INTEGER(d3)[0] = n_obs; INTEGER(d3)[1] = n_vars; INTEGER(d3)[2] = ns1;
  SEXP wx = PROTECT(Rf_allocArray(REALSXP, d3));
  SEXP wp = PROTECT(Rf_allocMatrix(REALSXP, n_params, ns1));
  SEXP d4 = PROTECT(Rf_allocVector(INTSXP, 4));
  INTEGER(d4)[0] = n_obs; INTEGER(d4)[1] = n_vars;
  INTEGER(d4)[2] = ns1;   INTEGER(d4)[3] = nd1;
  SEXP dwx = PROTECT(Rf_allocArray(REALSXP, d4));
  SEXP d3p = PROTECT(Rf_allocVector(INTSXP, 3));
  INTEGER(d3p)[0] = n_params; INTEGER(d3p)[1] = ns1; INTEGER(d3p)[2] = nd1;
  SEXP dwp = PROTECT(Rf_allocArray(REALSXP, d3p));
  {modelname}_vjp_ad_impl(REAL(xS), Rf_isNull(pS) ? nullptr : REAL(pS), REAL(wS),
      Rf_isNull(vxS) ? nullptr : REAL(vxS),
      Rf_isNull(vpS) ? nullptr : REAL(vpS),
      Rf_isNull(dwS) ? nullptr : REAL(dwS),
      REAL(y), REAL(wx), REAL(wp), REAL(dwx), REAL(dwp),
      n_obs, n_vars, n_params, n_out, n_seed, n_dir);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, 5));
  SET_VECTOR_ELT(out, 0, y);
  SET_VECTOR_ELT(out, 1, wx);
  SET_VECTOR_ELT(out, 2, wp);
  SET_VECTOR_ELT(out, 3, dwx);
  SET_VECTOR_ELT(out, 4, dwp);
  UNPROTECT(9);
  return out;
}}

""")
    if ad2:
        buf.write(f"""SEXP {modelname}_eval_ad2_c(SEXP xS, SEXP pS, SEXP dXS, SEXP dPS,
                        SEXP dX2S, SEXP dP2S, SEXP nS, SEXP nthS) {{
  const int n_obs = INTEGER(nS)[0], n_theta = INTEGER(nthS)[0];
  const int n_vars = {n_vars}, n_params = {n_params}, n_out = {n_out};
  const int nt1 = n_theta > 0 ? n_theta : 1;
  SEXP y = PROTECT(Rf_allocMatrix(REALSXP, n_obs, n_out));
  SEXP d1 = PROTECT(Rf_allocVector(INTSXP, 3));
  INTEGER(d1)[0] = n_obs; INTEGER(d1)[1] = n_out; INTEGER(d1)[2] = nt1;
  SEXP dy = PROTECT(Rf_allocArray(REALSXP, d1));
  SEXP d2 = PROTECT(Rf_allocVector(INTSXP, 4));
  INTEGER(d2)[0] = n_obs; INTEGER(d2)[1] = n_out;
  INTEGER(d2)[2] = nt1;   INTEGER(d2)[3] = nt1;
  SEXP d2y = PROTECT(Rf_allocArray(REALSXP, d2));
  {modelname}_eval_ad2_impl(REAL(xS), REAL(pS),
      Rf_isNull(dXS) ? nullptr : REAL(dXS),
      Rf_isNull(dPS) ? nullptr : REAL(dPS),
      Rf_isNull(dX2S) ? nullptr : REAL(dX2S),
      Rf_isNull(dP2S) ? nullptr : REAL(dP2S),
      REAL(y), REAL(dy), REAL(d2y), n_obs, n_vars, n_params, n_out, n_theta);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, 3));
  SET_VECTOR_ELT(out, 0, y);
  SET_VECTOR_ELT(out, 1, dy);
  SET_VECTOR_ELT(out, 2, d2y);
  UNPROTECT(6);
  return out;
}}

""")


def _write_vjp_ad_impl(buf, modelname, ctx, out_names):
    """The same contraction over a dual, which is forward over reverse.

    Both terms of d/dv (w' J) fall out of one pass: the Jacobian differentiated
    along the tangents the inputs carry, and the Jacobian contracted with the
    tangents the cotangent carries. No Hessian is emitted and none is stored.
    """
    n_vars = len(ctx.variables)
    n_params = len(ctx.parameters)
    n_out = len(out_names)
    buf.write(f"""static void {modelname}_vjp_ad_impl(
    const double* x, const double* p, const double* w,
    const double* vx, const double* vp, const double* dw,
    double* y, double* wx, double* wp, double* dwx, double* dwp,
    int n_obs, int n_vars, int n_params, int n_out, int n_seed, int n_dir) {{
  using AD = cppde::dual<double, 0>;
  // One scope for the whole call: the vectors below outlive any per-obs one.
  cppde::dual_arena::scope _vjp_ad_scope;
  const size_t ns1 = (size_t)(n_seed > 0 ? n_seed : 1);
  const size_t nw  = (size_t)n_obs * (size_t)n_out * ns1;
  std::vector<AD> x_ad((size_t)n_obs * (size_t)n_vars);
  std::vector<AD> p_ad((size_t)n_params);
  std::vector<AD> w_ad(nw);
  std::vector<AD> y_ad((size_t)n_obs * (size_t)n_out);
  std::vector<AD> wx_ad((size_t)n_obs * (size_t)n_vars * ns1);
  std::vector<AD> wp_ad((size_t)n_params * ns1);

  auto seed = [&](AD& a, double v, const double* tan, size_t stride) {{
    a.x() = v;
    if (n_dir > 0) {{
      a.diff(0, n_dir);
      for (int k = 0; k < n_dir; ++k) a[k] = tan ? tan[stride * (size_t)k] : 0.0;
    }}
  }};

  for (size_t i = 0; i < x_ad.size(); ++i)
    seed(x_ad[i], x[i], vx ? vx + i : nullptr, (size_t)n_obs * (size_t)n_vars);
  for (size_t j = 0; j < p_ad.size(); ++j)
    seed(p_ad[j], p[j], vp ? vp + j : nullptr, (size_t)n_params);
  for (size_t i = 0; i < nw; ++i)
    seed(w_ad[i], w[i], dw ? dw + i : nullptr, nw);

  {modelname}_vjp_impl<AD>(x_ad.data(), p_ad.data(), w_ad.data(),
                           y_ad.data(), wx_ad.data(), wp_ad.data(),
                           n_obs, n_vars, n_params, n_out, n_seed);

  for (size_t i = 0; i < y_ad.size(); ++i) y[i] = y_ad[i].val();
  for (size_t i = 0; i < wx_ad.size(); ++i) {{
    wx[i] = wx_ad[i].val();
    for (int k = 0; k < n_dir; ++k) dwx[i + wx_ad.size() * (size_t)k] = wx_ad[i].d(k);
  }}
  for (size_t i = 0; i < wp_ad.size(); ++i) {{
    wp[i] = wp_ad[i].val();
    for (int k = 0; k < n_dir; ++k) dwp[i + wp_ad.size() * (size_t)k] = wp_ad[i].d(k);
  }}
}}

""")


def _write_vjp_function(buf, modelname):
    buf.write(
        f"void {modelname}_vjp(double* x, double* p, double* w,\n"
        f"                     double* y, double* wx, double* wp,\n"
        f"                     int* n_obs_p, int* n_vars_p, int* n_params_p,\n"
        f"                     int* n_out_p, int* n_seed_p) {{\n"
        f"    {modelname}_vjp_impl<double>(x, p, w, y, wx, wp, *n_obs_p, *n_vars_p,\n"
        f"                         *n_params_p, *n_out_p, *n_seed_p);\n"
        "}\n\n"
    )


def _write_eval_ad_batch(buf, modelname):
    """Emit the .Call batch entry for the AD evaluator.

    One call evaluates many argument sets. R API only before and after the
    parallel region, mirroring cppde_r_batch.hpp: outputs are allocated up
    front so workers write straight into R memory.
    """
    buf.write(f"""SEXP {modelname}_eval_ad_batch(SEXP sets, SEXP nthreadsSEXP) {{
  const int K = Rf_length(sets);
  const int nt_req = Rf_isNull(nthreadsSEXP) ? 0 : INTEGER(nthreadsSEXP)[0];

  std::vector<const double*> X(K), P(K), DX(K), DP(K);
  std::vector<double*> Y(K), DY(K);
  std::vector<int> NOBS(K), NVAR(K), NPAR(K), NOUT(K), NTH(K);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, K));

  for (int k = 0; k < K; ++k) {{
    SEXP s = VECTOR_ELT(sets, k);
    X[k]  = REAL(VECTOR_ELT(s, 0));
    P[k]  = REAL(VECTOR_ELT(s, 1));
    DX[k] = Rf_isNull(VECTOR_ELT(s, 2)) ? nullptr : REAL(VECTOR_ELT(s, 2));
    DP[k] = Rf_isNull(VECTOR_ELT(s, 3)) ? nullptr : REAL(VECTOR_ELT(s, 3));
    NOBS[k] = INTEGER(VECTOR_ELT(s, 4))[0];
    NVAR[k] = INTEGER(VECTOR_ELT(s, 5))[0];
    NPAR[k] = INTEGER(VECTOR_ELT(s, 6))[0];
    NOUT[k] = INTEGER(VECTOR_ELT(s, 7))[0];
    NTH[k]  = INTEGER(VECTOR_ELT(s, 8))[0];

    SEXP pair = PROTECT(Rf_allocVector(VECSXP, 2));
    SEXP yv = PROTECT(Rf_allocMatrix(REALSXP, NOBS[k], NOUT[k]));
    Y[k] = REAL(yv);
    SET_VECTOR_ELT(pair, 0, yv);
    SEXP dd = PROTECT(Rf_allocVector(INTSXP, 3));
    INTEGER(dd)[0] = NOBS[k]; INTEGER(dd)[1] = NOUT[k];
    INTEGER(dd)[2] = NTH[k] > 0 ? NTH[k] : 1;
    SEXP dv = PROTECT(Rf_allocArray(REALSXP, dd));
    DY[k] = REAL(dv);
    SET_VECTOR_ELT(pair, 1, dv);
    SET_VECTOR_ELT(out, k, pair);
    UNPROTECT(4);
  }}

  int nt = (nt_req > 0) ? nt_req : 1;
  if (nt > K) nt = K;
#ifdef _OPENMP
  if (omp_in_parallel()) nt = 1;
#pragma omp parallel for schedule(dynamic) num_threads(nt) if (nt > 1)
#endif
  for (int k = 0; k < K; ++k) {{
    try {{
      {modelname}_eval_ad_impl(X[k], P[k], DX[k], DP[k], Y[k], DY[k],
                               NOBS[k], NVAR[k], NPAR[k], NOUT[k], NTH[k]);
    }} catch (...) {{
      const size_t ny = (size_t)NOBS[k] * (size_t)NOUT[k];
      std::fill(Y[k], Y[k] + ny, std::numeric_limits<double>::quiet_NaN());
      std::fill(DY[k], DY[k] + ny * (size_t)(NTH[k] > 0 ? NTH[k] : 1),
                std::numeric_limits<double>::quiet_NaN());
    }}
  }}

  UNPROTECT(1);
  return out;
}}

""")


def _write_eval_ad2_batch(buf, modelname):
    """Emit the .Call batch entry for the nested-dual AD evaluator.

    Same contract as `_eval_ad_batch`: R API only before and after the
    parallel region, outputs allocated up front so workers write into R
    memory. Second-order seeds are optional per set.
    """
    buf.write(f"""SEXP {modelname}_eval_ad2_batch(SEXP sets, SEXP nthreadsSEXP) {{
  const int K = Rf_length(sets);
  const int nt_req = Rf_isNull(nthreadsSEXP) ? 0 : INTEGER(nthreadsSEXP)[0];

  std::vector<const double*> X(K), P(K), DX(K), DP(K), DX2(K), DP2(K);
  std::vector<double*> Y(K), DY(K), D2Y(K);
  std::vector<int> NOBS(K), NVAR(K), NPAR(K), NOUT(K), NTH(K);
  SEXP out = PROTECT(Rf_allocVector(VECSXP, K));

  for (int k = 0; k < K; ++k) {{
    SEXP s = VECTOR_ELT(sets, k);
    X[k]   = REAL(VECTOR_ELT(s, 0));
    P[k]   = REAL(VECTOR_ELT(s, 1));
    DX[k]  = Rf_isNull(VECTOR_ELT(s, 2)) ? nullptr : REAL(VECTOR_ELT(s, 2));
    DP[k]  = Rf_isNull(VECTOR_ELT(s, 3)) ? nullptr : REAL(VECTOR_ELT(s, 3));
    DX2[k] = Rf_isNull(VECTOR_ELT(s, 4)) ? nullptr : REAL(VECTOR_ELT(s, 4));
    DP2[k] = Rf_isNull(VECTOR_ELT(s, 5)) ? nullptr : REAL(VECTOR_ELT(s, 5));
    NOBS[k] = INTEGER(VECTOR_ELT(s, 6))[0];
    NVAR[k] = INTEGER(VECTOR_ELT(s, 7))[0];
    NPAR[k] = INTEGER(VECTOR_ELT(s, 8))[0];
    NOUT[k] = INTEGER(VECTOR_ELT(s, 9))[0];
    NTH[k]  = INTEGER(VECTOR_ELT(s, 10))[0];

    const int nth = NTH[k] > 0 ? NTH[k] : 1;
    SEXP triple = PROTECT(Rf_allocVector(VECSXP, 3));
    SEXP yv = PROTECT(Rf_allocMatrix(REALSXP, NOBS[k], NOUT[k]));
    Y[k] = REAL(yv);
    SET_VECTOR_ELT(triple, 0, yv);
    SEXP d1 = PROTECT(Rf_allocVector(INTSXP, 3));
    INTEGER(d1)[0] = NOBS[k]; INTEGER(d1)[1] = NOUT[k]; INTEGER(d1)[2] = nth;
    SEXP dv = PROTECT(Rf_allocArray(REALSXP, d1));
    DY[k] = REAL(dv);
    SET_VECTOR_ELT(triple, 1, dv);
    SEXP d2 = PROTECT(Rf_allocVector(INTSXP, 4));
    INTEGER(d2)[0] = NOBS[k]; INTEGER(d2)[1] = NOUT[k];
    INTEGER(d2)[2] = nth;     INTEGER(d2)[3] = nth;
    SEXP d2v = PROTECT(Rf_allocArray(REALSXP, d2));
    D2Y[k] = REAL(d2v);
    SET_VECTOR_ELT(triple, 2, d2v);
    SET_VECTOR_ELT(out, k, triple);
    UNPROTECT(6);
  }}

  int nt = (nt_req > 0) ? nt_req : 1;
  if (nt > K) nt = K;
#ifdef _OPENMP
  if (omp_in_parallel()) nt = 1;
#pragma omp parallel for schedule(dynamic) num_threads(nt) if (nt > 1)
#endif
  for (int k = 0; k < K; ++k) {{
    try {{
      {modelname}_eval_ad2_impl(X[k], P[k], DX[k], DP[k], DX2[k], DP2[k],
                                Y[k], DY[k], D2Y[k],
                                NOBS[k], NVAR[k], NPAR[k], NOUT[k], NTH[k]);
    }} catch (...) {{
      const int nth = NTH[k] > 0 ? NTH[k] : 1;
      const size_t ny = (size_t)NOBS[k] * (size_t)NOUT[k];
      std::fill(Y[k],   Y[k]   + ny, std::numeric_limits<double>::quiet_NaN());
      std::fill(DY[k],  DY[k]  + ny * (size_t)nth,
                std::numeric_limits<double>::quiet_NaN());
      std::fill(D2Y[k], D2Y[k] + ny * (size_t)nth * (size_t)nth,
                std::numeric_limits<double>::quiet_NaN());
    }}
  }}

  UNPROTECT(1);
  return out;
}}

""")


def _write_eval_ad2_function(buf, out_names, ctx, modelname, as_impl=False):
    """
    Generate extern-C nested-dual AD entry. Computes y, dy, d2y in one pass on
    cppde::dual<cppde::dual<double, 0>, 0>. Accepts first-order seeds dX,
    dP and optional second-order seeds dX2, dP2 (controlled by has_dX2,
    has_dP2 flags so length-zero R vectors stay safe).

    Layouts (R column-major):
      x   [n_vars, n_obs]
      p   [n_params]
      dX  [n_obs, n_vars, n_theta]
      dP  [n_params, n_theta]
      dX2 [n_obs, n_vars, n_theta, n_theta]   (skipped if has_dX2 == 0)
      dP2 [n_params, n_theta, n_theta]        (skipped if has_dP2 == 0)
      y   [n_obs, n_out]
      dy  [n_obs, n_out, n_theta]
      d2y [n_obs, n_out, n_theta, n_theta]
    """
    n_vars = len(ctx.variables)
    n_params = len(ctx.parameters)
    n_out = len(out_names)

    inner_t = "cppde::dual<double, 0>"
    outer_t = "cppde::dual2nd<double, 0>"

    # The body lives in an impl taking values, so the .C entry and the batch
    # entry share it. The batch entry calls it from worker threads.
    if as_impl:
        buf.write(
            f"static void {modelname}_eval_ad2_impl(const double* x, const double* p,\n"
            f"                          const double* dX, const double* dP,\n"
            f"                          const double* dX2, const double* dP2,\n"
            f"                          double* y, double* dy, double* d2y,\n"
            f"                          int n_obs, int n_vars, int n_params,\n"
            f"                          int n_out, int n_theta) {{\n"
        )
        buf.write(f"    using inner_t = {inner_t};\n")
        buf.write(f"    using AD      = {outer_t};\n")
        buf.write("    (void)n_vars; (void)n_params; (void)n_out;\n")
        buf.write("    (void)dX; (void)dP;\n")
        buf.write("    (void)dX2; (void)dP2;\n\n")
    else:
        buf.write(
            f"void {modelname}_eval_ad2(double* x, double* p,\n"
            f"                          double* dX, double* dP,\n"
            f"                          double* dX2_in, double* dP2_in,\n"
            f"                          int* has_dX2, int* has_dP2,\n"
            f"                          double* y, double* dy, double* d2y,\n"
            f"                          int* n_obs_p, int* n_vars_p, int* n_params_p,\n"
            f"                          int* n_out_p, int* n_theta_p) {{\n"
        )
        buf.write(f"    {modelname}_eval_ad2_impl(x, p, dX, dP,\n")
        buf.write("                              (*has_dX2) ? dX2_in : nullptr,\n")
        buf.write("                              (*has_dP2) ? dP2_in : nullptr,\n")
        buf.write("                              y, dy, d2y,\n")
        buf.write("                              *n_obs_p, *n_vars_p, *n_params_p,\n")
        buf.write("                              *n_out_p, *n_theta_p);\n")
        buf.write("}\n\n")
        return

    buf.write("    cppde::dual_arena::scope _eval_ad2_scope;\n")
    buf.write(f"    std::vector<AD> x_ad({n_vars});\n")
    buf.write(f"    std::vector<AD> p_ad({n_params});\n")
    buf.write(f"    std::vector<AD> y_ad({n_out});\n\n")

    if n_params > 0:
        buf.write("    // Seed parameters once (constant across obs).\n")
        buf.write("    for (int j = 0; j < n_params; ++j) {\n")
        buf.write("        // Innermost scalar value\n")
        buf.write("        p_ad[j].scalar() = p[j];\n")
        buf.write("        if (n_theta > 0) {\n")
        buf.write("            // Outer tangent layer: inline gradient slot k = dP[j, k];\n")
        buf.write("            // inner tangent slot m = dP2[j, k, m] (Hessian row k).\n")
        buf.write("            p_ad[j].diff(0, n_theta);\n")
        buf.write("            for (int k = 0; k < n_theta; ++k) {\n")
        buf.write("                p_ad[j][k].x() = dP[j + (size_t)n_params * k];\n")
        buf.write("                if (dP2 != nullptr) {\n")
        buf.write("                    p_ad[j][k].diff(0, n_theta);\n")
        buf.write("                    for (int m = 0; m < n_theta; ++m)\n")
        buf.write("                        p_ad[j][k][m] = dP2[j + (size_t)n_params * (k + (size_t)n_theta * m)];\n")
        buf.write("                }\n")
        buf.write("            }\n")
        buf.write("        }\n")
        buf.write("    }\n\n")

    buf.write("    for (int obs = 0; obs < n_obs; ++obs) {\n")
    if n_vars > 0:
        buf.write("        for (int j = 0; j < n_vars; ++j) {\n")
        buf.write("            // Innermost scalar value\n")
        buf.write("            x_ad[j].scalar() = x[obs + (size_t)n_obs * j];\n")
        buf.write("            if (n_theta > 0) {\n")
        buf.write("                // Outer tangent layer: inline gradient slot k = dX[obs, j, k];\n")
        buf.write("                // inner tangent slot m = dX2[obs, j, k, m] (Hessian row k)\n")
        buf.write("                x_ad[j].diff(0, n_theta);\n")
        buf.write("                for (int k = 0; k < n_theta; ++k) {\n")
        buf.write("                    x_ad[j][k].x() = dX[obs + (size_t)n_obs * (j + (size_t)n_vars * k)];\n")
        buf.write("                    if (dX2 != nullptr) {\n")
        buf.write("                        x_ad[j][k].diff(0, n_theta);\n")
        buf.write("                        for (int m = 0; m < n_theta; ++m)\n")
        buf.write("                            x_ad[j][k][m] = dX2[obs + (size_t)n_obs * (j + (size_t)n_vars * (k + (size_t)n_theta * m))];\n")
        buf.write("                    }\n")
        buf.write("                }\n")
        buf.write("            }\n")
        buf.write("        }\n")
    buf.write(f"        {modelname}_eval_one<AD>(x_ad.data(), p_ad.data(), y_ad.data());\n")
    buf.write("        for (int i = 0; i < n_out; ++i) {\n")
    # Read through a const reference so d1_at / dd_at take the bounds-safe const
    # overloads, which return a thread-local zero for a non-depend tangent layer.
    # The non-const ones dereference the inner tan_ and fault on an unseeded seed.
    buf.write("            const AD& y_const = y_ad[i];\n")
    buf.write("            y[obs + (size_t)n_obs * i] = y_const.scalar();\n")
    buf.write("            for (int k = 0; k < n_theta; ++k) {\n")
    buf.write("                // dy / d2y read from outer tangent slots (inline gradient and\n")
    buf.write("                // Hessian rows). Const overloads of d1_at / dd_at are bounds-safe;\n")
    buf.write("                // the non-const ones assume armed storage and would deref the\n")
    buf.write("                // inner tan_ for outputs constant in all parameters.\n")
    buf.write("                dy[obs + (size_t)n_obs * (i + (size_t)n_out * k)] = y_const.d1_at(k);\n")
    buf.write("                for (int m = 0; m < n_theta; ++m) {\n")
    buf.write("                    d2y[obs + (size_t)n_obs * (i + (size_t)n_out * (k + (size_t)n_theta * m))]\n")
    buf.write("                        = y_const.dd_at(k, m);\n")
    buf.write("                }\n")
    buf.write("            }\n")
    buf.write("        }\n")
    buf.write("    }\n}\n\n")
