## base gained `%||%` in R 4.4.0; the package supports R >= 4.0.
`%||%` <- function(x, y) if (is.null(x)) y else x

#' Disambiguate a model name against currently loaded shared libraries.
#'
#' Overwriting a shared object that is already loaded is unreliable across
#' platforms: `dyn.unload()` may leave file handles open, notably on Windows,
#' and R keeps serving the old code until the file is replaced. To avoid this,
#' the constructors call `unique_modelname()` right after fixing `modelname`.
#' If a DLL of that base name is already loaded, a numeric suffix (`_2`, `_3`,
#' ...) is appended and a warning is issued.
#'
#' @param modelname Character scalar: the desired base name.
#' @return The original name if free, otherwise `modelname_<i>` for the
#'   smallest free `i >= 2`.
#' @keywords internal
#' @noRd
unique_modelname <- function(modelname) {
  loaded <- names(getLoadedDLLs())
  if (!modelname %in% loaded) return(modelname)
  i <- 2L
  repeat {
    cand <- paste0(modelname, "_", i)
    if (!cand %in% loaded) {
      warning(sprintf(
        "A shared library named '%s' is already loaded; reliably overwriting it across platforms is not supported. Using '%s' instead.",
        modelname, cand), call. = FALSE)
      return(cand)
    }
    i <- i + 1L
  }
}

# --- Native symbol resolution ---
## Dispatch is by (symbol name, DLL name), never by a resolved address:
## dyn.unload() nulls every address handed out so far, in place, and nothing
## resolves them again. Only the name pairing is remembered, which nothing
## but a recompile can invalidate.
.symDLL <- new.env(parent = emptyenv())

## Entry point `name` and the DLL exporting it, or NULL when nothing does.
.nativeSym <- function(name) {
  dll <- get0(name, envir = .symDLL, inherits = FALSE)
  if (!is.null(dll)) return(list(name = name, dll = dll))
  if (!is.loaded(name)) return(NULL)
  dll <- tryCatch(getNativeSymbolInfo(name)$dll[["name"]], error = function(e) NULL)
  if (is.null(dll)) return(NULL)
  assign(name, dll, envir = .symDLL)
  list(name = name, dll = dll)
}

## Drop-in for .Call() / .C(). Naming the DLL keeps the lookup from scanning
## every loaded shared object and from reaching another model's entry point.
.callSym <- function(sym, ...) .Call(sym$name, ..., PACKAGE = sym$dll)
.cSym    <- function(sym, ...) .C(sym$name, ..., PACKAGE = sym$dll)

#' Forget which shared object exports which entry point
#'
#' [funCpp] instances and [solveODE] remember the DLL that exports each
#' generated entry point, so that a call does not have to search every loaded
#' shared object. Recompiling a model into a differently named shared object
#' makes that pairing stale. Call this to drop it; [compile] does it for you.
#'
#' Addresses are never cached, so this is not needed after loading or unloading
#' a shared object.
#'
#' @return `NULL`, invisibly.
#' @export
clearNativeSymbols <- function() {
  rm(list = ls(.symDLL, all.names = TRUE), envir = .symDLL)
  invisible(NULL)
}

#' Compile Generated C++ Model Code
#'
#' @description
#' Compiles one or more C++ source files generated by [cppODE()] or
#' [funCpp()] into shared libraries (`.so` or `.dll`) using
#' `R CMD SHLIB`. Compile-time flags stored in each object's
#' `"compileArgs"` attribute are picked up automatically; further flags
#' may be passed through `args`.
#'
#' @section Environment variables:
#' `CPPDE_EXTRA_CXXFLAGS` is appended to the compiler flags of every
#' model compiled in the session, after `"compileArgs"` and `args`. Use
#' it to apply a define, an `-march` setting or a sanitizer to a whole
#' run without touching the call sites. Exporting `PKG_CXXFLAGS` has no
#' effect: `compile()` sets that variable itself.
#'
#' `CPPDE_EXTRA_LIBS` is the linker counterpart, appended last to
#' `PKG_LIBS`. A sanitizer needs both: `CPPDE_EXTRA_CXXFLAGS` and
#' `CPPDE_EXTRA_LIBS` set to `-fsanitize=thread` builds and links the
#' generated models under ThreadSanitizer.
#'
#' @param ... One or more objects returned by [cppODE()] or [funCpp()]
#'   that carry a `"srcfile"` attribute.
#' @param output Optional base name for a combined shared library.
#' @param args Optional additional compiler or linker arguments appended
#'   after the flags from `"compileArgs"`.
#' @param cores Number of parallel compilation jobs (Unix only).
#' @param verbose Logical; if `TRUE`, show compiler commands.
#'
#' @return Invisibly returns `TRUE` on successful compilation.
#' @export
compile <- function(..., output = NULL, args = NULL, cores = 1, verbose = FALSE) {

  ## save & restore env
  old <- Sys.getenv(c("PKG_CFLAGS", "PKG_CXXFLAGS", "PKG_CPPFLAGS", "PKG_LIBS"), unset = NA)
  on.exit({
    for (n in names(old))
      if (is.na(old[n])) Sys.unsetenv(n) else Sys.setenv(structure(old[n], names = n))
  }, add = TRUE)

  objects <- list(...)
  Rbin <- file.path(R.home("bin"), "R")   # unquoted: system2() quotes it
  so   <- .Platform$dynlib.ext

  # --- collect source files ---
  files <- unique(unlist(lapply(objects, function(obj) {
    src <- attr(obj, "srcfile")
    if (!is.null(src) && file.exists(src))
      normalizePath(src, winslash = "/", mustWork = FALSE)
  })))
  if (!length(files))
    stop("No valid C/C++ source files found for compilation.")

  roots      <- sub("\\.[^.]+$", "", basename(files))
  roots_full <- sub("\\.[^.]+$", "", files)

  # --- merge compileArgs from objects with explicit args ---
  obj_args <- unique(unlist(lapply(objects, function(obj) {
    a <- attr(obj, "compileArgs")
    if (!is.null(a) && nzchar(a)) a else NULL
  })))
  all_args <- paste(c(obj_args, args), collapse = " ")

  # --- extra linker flags from objects (linkArgs) ---
  obj_linkargs <- unique(unlist(lapply(objects, function(obj) {
    a <- attr(obj, "linkArgs")
    if (!is.null(a) && nzchar(a)) a else NULL
  })))
  extra_libs <- paste(obj_linkargs, collapse = " ")

  # --- compiler flags ---
  if (.Platform$OS.type == "windows") cores <- 1
  pic  <- if (.Platform$OS.type == "windows") "" else "-fPIC"
  base <- paste("-O2 -DNDEBUG -w", pic)

  # --- LAPACK (always available via R) ---
  cfg <- function(x) {
    out <- suppressWarnings(system2(Rbin, c("CMD", "config", x), stdout = TRUE))
    if (length(out)) paste(trimws(out), collapse = " ") else ""
  }
  lapack_libs <- cfg("LAPACK_LIBS")
  blas_libs   <- cfg("BLAS_LIBS")

  # --- KLU (system SuiteSparse, discovered by ./configure at install) ---
  uses_sparse <- any(vapply(objects, function(obj) {
    isTRUE(attr(obj, "sparse"))
  }, logical(1)))

  klu_libs   <- ""
  klu_cflags <- ""

  ## The constructors record the flags their model was generated for, so that a
  ## consumer building the shared object itself gets them. Adding a group that
  ## is already there would only repeat it on the command line.
  unlessPresent <- function(flags, present)
    if (nzchar(flags) && grepl(flags, present, fixed = TRUE)) "" else flags

  if (uses_sparse) {
    if (!isTRUE(cvodeConfig$klu_available)) {
      stop(
        "Sparse Jacobian requested but the KLU linear solver was not\n",
        "available at install time.\n",
        "  Build SuiteSparse/KLU from source into a per-user cache, no\n",
        "  administrator rights required:\n",
        "      cppDE::install_libs(\"suitesparse\")\n",
        "  then run the re-install command it prints. Alternatively install\n",
        "  the SuiteSparse development headers system-wide and re-install:\n",
        "    Debian/Ubuntu : sudo apt install libsuitesparse-dev\n",
        "    Fedora        : sudo dnf install suitesparse-devel\n",
        "    Arch          : sudo pacman -S suitesparse\n",
        "    macOS (brew)  : brew install suite-sparse\n",
        "    Windows       : from any shell (PowerShell / cmd / Git Bash)\n",
        "                    call Rtools' pacman by full path -- substitute\n",
        "                    your installed version for <ver> (e.g. 44 or 45):\n",
        "                      C:/rtools<ver>/usr/bin/pacman.exe -Sy --noconfirm mingw-w64-ucrt-x86_64-suitesparse\n",
        "  Then: R CMD INSTALL <path/to/cppDE>",
        call. = FALSE)
    }
    klu_cflags <- paste("-DKLU", unlessPresent(cvodeConfig$klu_cflags, all_args))
    klu_libs   <- unlessPresent(cvodeConfig$klu_libs, extra_libs)
  }

  ## OpenMP, when configure could actually link it.  Absent, the generated
  ## batch entry compiles to a serial loop via #ifdef _OPENMP.
  omp_cxxflags <- if (isTRUE(cvodeConfig$openmp_available))
    unlessPresent(cvodeConfig$openmp_cxxflags, all_args) else ""
  omp_libs     <- if (isTRUE(cvodeConfig$openmp_available))
    unlessPresent(cvodeConfig$openmp_libs, extra_libs) else ""

  cxxflagsString <- paste(base, klu_cflags, omp_cxxflags)
  if (nzchar(all_args)) cxxflagsString <- paste(cxxflagsString, all_args)
  ## Session-wide extra flags, appended last (see ?compile).
  extra_cxxflags <- Sys.getenv("CPPDE_EXTRA_CXXFLAGS")
  if (nzchar(extra_cxxflags))
    cxxflagsString <- paste(cxxflagsString, extra_cxxflags)
  ## Linker counterpart: a sanitizer has to reach the link line too.
  extra_ldflags <- Sys.getenv("CPPDE_EXTRA_LIBS")
  ## Empty groups leave runs of blanks behind, which reach the toolchain report.
  squeeze <- function(x) gsub("[[:space:]]+", " ", trimws(x))
  Sys.setenv(
    PKG_CXXFLAGS = squeeze(cxxflagsString),
    PKG_CPPFLAGS = paste0("-I", system.file("include", package = "cppDE")),
    PKG_LIBS = squeeze(paste(klu_libs, lapack_libs, blas_libs, omp_libs,
                             extra_libs, extra_ldflags))
  )

  # --- toolchain report ---
  strip <- function(x) trimws(gsub("(^| )-std=[^ ]+", "", x))
  if (any(grepl("\\.cpp$", files)))
    cat(sprintf("using C++ compiler: %s [%s]\n",
                strip(cfg("CXX")), trimws(Sys.getenv("PKG_CXXFLAGS"))))

  # --- unload stale DLLs ---
  unload_and_delete <- function(basename_no_ext, so_path) {
    loaded <- getLoadedDLLs()
    if (basename_no_ext %in% names(loaded))
      try(dyn.unload(loaded[[basename_no_ext]][["path"]]), silent = TRUE)
    if (file.exists(so_path)) try(unlink(so_path), silent = TRUE)
  }

  if (is.null(output)) {
    invisible(mapply(unload_and_delete,
                     roots, paste0(roots_full, so),
                     SIMPLIFY = FALSE))
  } else {
    try(dyn.unload(paste0(output, so)), silent = TRUE)
  }

  ## A freshly linked library intermittently fails to load on Windows right
  ## after R CMD SHLIB returns; retry before giving up.
  load_dll <- function(path) {
    for (i in 1:10) {
      if (!inherits(try(dyn.load(path), silent = TRUE), "try-error")) return(invisible(TRUE))
      Sys.sleep(0.2 * i)
    }
    dyn.load(path)
  }

  # --- compile ---
  ## Keep the toolchain output: it is the only diagnostic when a build fails.
  ## Capture it with system2(): Windows runs the command without a shell, so an
  ## appended "2>&1" reaches R CMD SHLIB as an argument and clobbers PKG_LIBS.
  run <- function(args) {
    if (verbose) {
      cat(paste(c(shQuote(Rbin), args), collapse = " "), "\n")
      if (system2(Rbin, args) != 0) stop("Compilation failed", call. = FALSE)
      return(invisible(character()))
    }
    out <- suppressWarnings(system2(Rbin, args, stdout = TRUE, stderr = TRUE))
    st  <- attr(out, "status")
    if (!is.null(st) && st != 0)
      stop("Compilation failed:\n", paste(out, collapse = "\n"), call. = FALSE)
    invisible(out)
  }

  ## R CMD SHLIB writes tmp.def and symbols.rds into the current directory, so
  ## builds sharing one clobber each other's def file; give each its own. Only
  ## those files are cwd-relative, sources and output are absolute.
  shlib <- function(args, tag) {
    wd <- tempfile(paste0("cppDE_build_", gsub("[^A-Za-z0-9._-]", "_", tag), "_"))
    if (!dir.create(wd, showWarnings = FALSE)) return(run(args))
    old <- setwd(wd)
    on.exit({ setwd(old); unlink(wd, recursive = TRUE) }, add = TRUE)
    run(args)
  }

  ## A zero exit status is not proof that the library was linked.
  built_or_stop <- function(paths, logs) {
    miss <- !file.exists(paths)
    if (any(miss))
      stop("R CMD SHLIB reported success but produced no ", so, " for ",
           paste(basename(paths[miss]), collapse = ", "), ":\n",
           paste(unlist(logs[miss]), collapse = "\n"), call. = FALSE)
  }

  if (is.null(output)) {
    build1 <- function(f)
      shlib(c("CMD", "SHLIB", shQuote(f)), sub("\\.[^.]+$", "", basename(f)))
    logs <- if (.Platform$OS.type == "unix" && cores > 1)
      parallel::mclapply(files, build1, mc.cores = cores)
    else
      lapply(files, build1)
    built_or_stop(paste0(roots_full, so), logs)
    for (r in roots_full) load_dll(paste0(r, so))
    clearNativeSymbols()
  } else {
    output <- sub(paste0("\\", so, "$"), "", output)
    outdir <- dirname(files[1])
    out_so <- file.path(outdir, paste0(output, so))
    try(dyn.unload(out_so), silent = TRUE)
    if (file.exists(out_so)) unlink(out_so)
    log <- shlib(c("CMD", "SHLIB", shQuote(files), "-o", shQuote(out_so)),
                 output)
    built_or_stop(out_so, list(log))
    load_dll(out_so)
    clearNativeSymbols()
  }

  invisible(TRUE)
}


## Drop srcrefs from every closure in `envir`. Lookup is by name at call time,
## so replacing the bindings also reaches the returned wrappers.
.stripSource <- function(envir) {
  for (nm in ls(envir, all.names = TRUE)) {
    v <- get0(nm, envir = envir, inherits = FALSE)
    if (is.function(v) && !is.primitive(v))
      assign(nm, utils::removeSource(v), envir = envir)
  }
  invisible(NULL)
}
